--data.raw["constant-combinator"]["constant-combinator"]			.collision_mask = {"doodad-layer"}
--data.raw["decider-combinator"]["decider-combinator"]			.collision_mask = {"doodad-layer"}
--data.raw["arithmetic-combinator"]["arithmetic-combinator"]		.collision_mask = {"doodad-layer"}
