-- TODO
--	inside - really long wire reach
--		Connector (Pole), autocreated
--		Constant
--		Decider
--		Speaker
--		Arithmetic
--	outside - invisible
--		Connector (Pole)
--		Constant
--		Decider
--		Speaker
--		Arithmetic
--	Mark combinator 
--		not recreated if primary entity is not opened, deleted after 5 minutes you don't open it
--	Green test entities & items - saved, but not recreated
--		Test input (=constant combinator)
--		Test decider 
--		Test arithmetic
--		Test programmable speaker
--	Primary entities 
-- 		2x2
--		3x3
--	Adjustment of size of initial created connectors
